README.md, README.txt, docs/Autores.md, docs/Guia_de_operacao-desenvolvimento.md, docs/Regras_versionamento.md, docs/Roteiro_de_publicacao_de_releases.md
Inserindo arquivos iniciais pra começar a ajustar a documentação.
=> [ ADD ] Inserindo arquivos iniciais pra começar a ajustar a documentação

emendas/classes/model/Beneficiario.inc
Correção para o erro de enviar o beneficiario para unidade através do botão do workflow.
=> [ FIX ] Emendas - Correção Workflow

docs/Autores.md
Adicionado Pedro Philipe Alves de Oliveira como autor
=> Adição de novo autor

www/planacomorc/_funcoes.php
=> Feature sentry

monitora/classes/Pi_PlanoInterno.class.inc, planacomorc/modulos/relatorio/funcionais-xls.inc, planacomorc/modulos/relatorio/funcionais.inc
Primeira versão do relatório de funcionais em fase de homologação pelo P.O do projeto.
Observação: Não excluir a branch :)
=> [ ADD ] Relatório de funcionais

monitora/classes/Pi_PlanoInterno.class.inc
Erro recebebido por e-mail automatico do sistema.
=> [ FIX ] Erro ao Abrir relatório Geral.

planacomorc/modulos/relatorio/funcionais.inc
Ao mesclar a branch que tinha a melhoria pra não exibir a paginação se perderam as atualizações de novas colunas do relatório.
=> [ FIX ] Relatório de Funcionais - Erro ao mesclar branchs

www/planacomorc/_funcoes.php
Mudança solicitada urgente pelo P.O do projeto para que ao invés dos usuários com perfil Planejamento sejam enviado e-mails para usuários do perfil Administrador.
=> Envio de e-mails

emendas/modulos/principal/beneficiario_form.inc, includes/cabecalho_bootstrap_v3.inc, zimec/public/temas/simec/css/simec.css
Correção nas cores do layout do sistema ao utilizar o componente de abas sob supervisão do webdesign pra armonizar o uso das telas. Forçando atualização do arquivo css em cache do browser.
=> [ FIX ] Emendas - Alteração no layout

docs/Guia_de_operacao-desenvolvimento.md
Corrigindo documentação de guia de operação e desenvolvimento.
=> [ UPDATE ] Documentação

includes/funcoes.inc, public/classes/Model/SubUnidadeOrcamentaria.inc, spo/classes/model/Planointerno.php
Correção pra casos em que o componente chosen com o parâmetro multi envia itens da lista em branco.
=> [ FIX ] Lista de PI.

global/config.inc-exemplo, includes/classes_simec.inc
Habilitando auditoria de dados.
=> [ NEW ] Auditoria

seguranca/modulos/sistema/workflow/cadastraTree_acao.inc
Correção para a tela de administrar menus exibir apenas os módulos ativos ao invés de em torno de 80 opções de módulos, dificultando a navegabilidade da tela que é usada constantemente em fases de desenvolvimento.
=> [ FIX ] Opção Sistema na tela Administrar Menus

includes/funcoes.inc, planacomorc/modulos/principal/unidade/email.inc, www/planacomorc/_funcoes.php
Correção na consulta que retorna os dados de funcionais e inserindo texto de devolução na mensagem de e-mail enviada para os usuários envolvidos no processo.
=> [ NEW ][ UPDATE ] Inserindo texto de devolução no envio de e-mail

includes/_funcoescadastrousuario.php, includes/email-template.php, seguranca/www/scripts_exec/spo_atualizarDotacao.php, www/cadastrar_usuario_2.php
Mudando o padrao do nome de arquivo do template de email.
=> [ ADD ][ REFACTORY ] Template de e-mail

global/config.inc-exemplo, planacomorc/modulos/principal/unidade/listapimanter-xls.inc, planacomorc/modulos/principal/unidade/listapimanter.inc, planacomorc/modulos/relatorio/funcionais.inc, www/planacomorc/js/unidade/lista-pi-manter.js
Inserindo recurso de exportar lista de PIs para o formato de planilha xls
=> [ ADD ][ UPDATE ] Inserindo recurso de exportar lista de PIs

includes/rodape.inc, includes/rodape_bootstrap_v3.inc
Retirando funcionalidade de exibir usuários on-line.
=> [ FIX ] Retirando Usuários on-line

planacomorc/modulos/principal/unidade/listapimanter-xls.inc
Retirando links do relatório da lista de PIs
=> [ FIX ] Retirando links do relatório da lista de PIs

includes/funcoes.inc, planacomorc/modulos/principal/unidade/detalhe-ptres.inc, planacomorc/modulos/principal/unidade/detalhe-subunidade.inc, planacomorc/modulos/principal/unidade/listapimanter.inc, planacomorc/modulos/principal/unidade/painel.inc
Funcionalidade marcar valores de vermelho quando os dados do SIAFI forem maiores que o valor planejado.
=> [ UPDATE ] Funcionalidade de Marcar Valores de Vermelho

acompanhamento/modulos/principal/monitorar-pi-cad.inc, planacomorc/modulos/inicio.inc, planacomorc/modulos/principal/unidade/cadastro_pi.inc, planacomorc/modulos/principal/unidade/painel.inc
Correção em regra de negócio para só permitir o monitoramento de PIs com códigos de empenho gerado.
=> [ FIX ] Aba Acompanhamento

acompanhamento/modulos/principal/monitorar-pi-cad.inc, acompanhamento/modulos/principal/monitorar-ppa.inc
Inserindo novo limite maximo de percentual dos graficos
=> [ UPDATE ] Limite dos Gráficos

planacomorc/modulos/principal/unidade/listapimanter.inc, www/planacomorc/js/unidade/lista-pi-manter.js
Correção para quando o sistema exportar a planilha não causar erro ao fazer consulta normal.
=> [ FIX ] Correção Exportar Planilha

emenda/classes/InterfaceSiconvMP.class.inc, global/config.inc-exemplo
Configurações termporarias de acesso.
=> [ UPDATE ] SICONV Configurações

emendas/modulos/apoio/proponente_form.inc, emendas/modulos/principal/beneficiario_form.inc, emendas/modulos/principal/grafico_coluna.inc
[ FIX ] Correção pra erro de tela apontado pelo P.O.
[ FIX ] Correção para o tipo de proponente ser obrigatório na tela de cadastro de Proponentes.
[ FIX ] Correção do botão de salvar pra validar corretamente os itens obrigatórios.
=> [ FIX ] Correção do botão de salvar pra validar corretamente

emendas/modulos/apoio/proponente_form.inc, emendas/modulos/principal/beneficiario_form.inc, emendas/modulos/principal/grafico_coluna.inc
[ FIX ] Correção pra erro de tela apontado pelo P.O.
[ FIX ] Correção para o tipo de proponente ser obrigatório na tela de cadastro de Proponentes.
[ FIX ] Correção do botão de salvar pra validar corretamente os itens obrigatórios na tela de cadastro de Beneficiários.
=> [ FIX ] Correção do botão de salvar pra validar corretamente os itens obrigatórios na tela de cadastro de Beneficiários.

emendas/classes/controller/Beneficiario.inc, emendas/classes/model/Emenda.inc, emendas/modulos/principal/emenda_form.inc
[ FIX ] Corrigindo a funcionalidade de excluir beneficiários. #158
=> [ FIX ] Corrigindo a funcionalidade de excluir beneficiários. #158

emendas/classes/controller/Beneficiario.inc, emendas/classes/model/Emenda.inc, emendas/classes/model/Siconv.inc, emendas/modulos/inicio.inc, emendas/modulos/principal/emenda.inc, emendas/modulos/principal/emenda_form.inc, seguranca/www/scripts_exec/spo_consultaSiconv.php
[ FIX ] Retirando paginação.
[ FIX ] Correção webservice SICONV.
[ FIX ] Corrigindo a funcionalidade de excluir beneficiários.
=> [ FIX ] Correção pras Unidades não verem os dados gerais do sistema.

emendas/classes/model/Emenda.inc, emendas/modulos/principal/emenda.inc
=> [ ADD ][ FIX ] Novas Colunas e Subunidades Visualizarem beneficiarios corretos

global/config.inc-exemplo
Organizando configurações do SICONV pra ficarem mais simples de configurar.
=> [ FIX ] Configurações WEBSERVICE SICONV

monitora/classes/controller/Acao.inc, monitora/classes/model/Acao.inc, monitora/classes/model/Programa.inc, planacomorc/modulos/apoio/acao.inc, planacomorc/modulos/apoio/acao_form.inc, public/classes/Model/Localizador.inc, public/classes/Model/ObjetivoPpa.inc
Há um conflito na model de ação.
rota: monitora/classes/model/Acao.inc
=> [ ADD ] Telas de Apoio - Ação

monitora/classes/controller/Acao.inc, monitora/classes/model/Acao.inc, monitora/classes/model/Programa.inc, planacomorc/modulos/apoio/acao.inc, planacomorc/modulos/apoio/acao_form.inc, public/classes/Model/Localizador.inc, public/classes/Model/ObjetivoPpa.inc
=> Hotfix issue 63

planacomorc/modulos/principal/unidade/listapimanter.inc, spo/classes/model/Planointerno.php, www/planacomorc/_funcoespi.php
Inserindo funcionalidade de Cancelar Pi.
=> [ UPDATE ] Funcionalidade de Cancelar PI

seguranca/www/scripts_exec/spo_atualizarDotacao.php
Correção no aviso de divergência entre valores empenhados da funcional Vs PIs. Fix #71
=> [ UPDATE ] Correção no aviso de divergência entre valores empenhados da funcional.

planacomorc/modulos/principal/unidade/listapimanter.inc, spo/classes/model/Planointerno.php
Correção do botão para filtro de emendas.
=>  [ FIX ] Lista PI filtro emendas. Issue #207

includes/funcoes.inc, seguranca/www/agendamentoscriptsexecutar.php
Correção de verficação de acesso das rotinas diarias.
=> [ FIX ] Rotinas diárias.

docs/Gerador.md
Após fazer o merge com a master, por favor deletar a branch README.
=> Documentação do gerador de código do SIMINC2

planacomorc/modulos/principal/unidade/cadastro_pi_fnc.inc, www/planacomorc/_funcoes.php
* Correção pra bug de não aparecer funcional no detalhamento do PI na tela de Cadastro de PI FNC no módulo Planejamento.
* Correção para exibir enquadramento Emendas no formulário de PI FNC.
=> [ FIX ] Funcionalidade de Gerar PI-Planejamento. Issue #221

www/emendas/_funcoes.php
Correção pra exibir corretamente o dado de convenio.
=> [ FIX ] Funcionalidade de Gerar PI(Dado de Convênio)

emendas/modulos/principal/emenda_form.inc
Correção na funcionalidade de cadastrar nova emenda.
=> [ FIX ] Tela de Cadastro de Emendas.

www/planacomorc/geral/cadastro_responsabilidade_ug.php, www/planacomorc/geral/cadastro_responsabilidade_uo.php, www/planacomorc/geral/cadastro_responsabilidades.php
Inclusão dos arquivos de administração de vinculo de unidades com perfis de usuários.
=> [ FIX ] Tela de Cadastro de Usuários - SIS

emendas/classes/controller/Beneficiario.inc, emendas/modulos/principal/beneficiario_form.inc, emendas/modulos/principal/beneficiariodetalhe.inc, emendas/modulos/principal/emendadetalhe.inc
Correção para aplicar regras corretamente de quando o sistema vai permitir o usuário excluir e editar detalhes financeiros e o próprio cadastro do Beneficiário.
=> Tela de Cadastro de Emenda e Beneficiário.

emendas/classes/controller/Beneficiario.inc, emendas/classes/model/Beneficiario.inc, emendas/classes/model/Emenda.inc
Implementando nova regra pra buscar proposta SICONV correta a partir do código da UO da Subunidade delegada.
=> [ UPDATE ] Emendas-Beneficiário-Funcionalidade de Atualizar Proposta SICONV

emendas/classes/model/Emenda.inc, emendas/modulos/principal/emenda.inc
Correção para não exibir funcionalidade para perfil Subunidade. Correção para exibir a funcionalidade pra todos que tem Proposta Siconv.
=> [ HOTFIX ] Tela Modal Selecionar Proposta.

emendas/classes/model/Beneficiario.inc, emendas/modulos/principal/emenda_form.inc
Excluir a coluna Esfera e forma de execução e incluir as colunas número da proposta, situação siconv,   custeio e capital empenhado, pago e um total em baixo ficando na seguinte ordem:  (5 pontos)
Ações / Proponente / Unidade / nº proposta / situação siconv / custeio / capital / empenhado / pago
e o total abaixo.
=> [ FIX ] Lista emendas na Tela de Cadastro de Beneficiários. Issue #325.

emendas/modulos/principal/emenda_form.inc
Invertido o campo de objetivo pelo o de localizador na combo de ptres.
=>  [ UPDATE ] Tela Emendas - Funcional da emenda

www/planacomorc/_funcoespi.php
Correção para o sistema não considerar os valores detalhados de PIs referntes a emendas.
=> [ FIX ] Limite de Subunidades.

planacomorc/modulos/principal/unidade/listapimanter.inc, spo/classes/model/Planointerno.php
Adicionado filtro de busca por ID do Beneficiário.
=> [ ADD ] Planejamento - Pesquisa de PI #322

emendas/modulos/principal/beneficiario_form.inc
Correção na opção de salvar e deletar GND.
=> [ FIX ] Correção GND 

emendas/modulos/principal/emenda_form.inc
Correção pra exibir o texto 'PTRES: ' ao mostrar o número do PTRES na opção Funcional da tela de cadastro.
=> [ UPDATE ] Inserindo PTRES no Formulário de Emendas. Issue #288

seguranca/modulos/principal/gerenciarespelhoperfil.inc, www/acompanhamento/geral/cadastro_responsabilidade_ug.php, www/acompanhamento/geral/cadastro_responsabilidades.php
Correção no espelhamento de perfil
=> [ FIX ] Perfil Unidade no SIS

sql/restore/homologacao-exemplo.sh, sql/restore/treinamento-exemplo.sh
=> [ FIX ] Rotinas diárias de restauração de base de dados.

includes/classes_simec.inc, includes/funcoes_espelhoperfil.php
Configurando arquivo secundário responsável por fazer espelhamento em lote.
=> [FIX] Correção Espelhamento de Perfil.

monitora/classes/model/Ptres.inc, proposta/modulos/inicio.inc, wssof/classes/Ws_MomentosDto.inc, www/proposta/proposta.php
Não esquecer de deletar a branch após a confirmação do merge e colcar a label de PUBLICADO no zenhub
=> [ FIX ] Funcionais sem dados de Objetivos. Issue #348

emendas/modulos/relatorio/geral.inc
Adicionado filtro que retorna apenas os registros das subunidades no relatório para o perfil Unidade
Co-authored-by: isaiassm <isaias1113@outlook.com>
=> [ FIX ] Relatório no perfil Unidade. Issue #205 

www/emendas/_funcoes.php, www/geral/workflow/alterar_estado.php
Correção ao usar envio de e-mail pelo componente Workflow.
=> [ FIX ] Notificação de e-mail na tramitação de beneficiários. Issue #251

www/planacomorc/_funcoes.php
Co-authored-by: isaiassm  <isaias1113@outlook.com >
=> [ FIX ] Planejamento Orçamentário - Correção pra fazer tramitação de PI.

includes/rodape_bootstrap_v3.inc, planacomorc/modulos/principal/unidade/espelho-pi.inc
Remoção de dados de impressão de quem abre no espelho de pi
Signed-off-by: Douglas <douglasantana007@gmail.com>
Co-authored-by: Isaiassm <isaias1113@outlook.com>
=> [CORREÇÃO] Remover dados de usuário e CPF da tela de espelho PI. Issue #326 

monitora/classes/Pi_PlanoInterno.class.inc
Correção no filtro de Acompanhamento Geral FNC que trazia Dados de funcionais de emendas (RP 6).
Co-authored-by: Isaiassm  <isaias1113@outlook.com>
=> [ FIX ] Emendas no painel fundo  - Remover funcionais emendas. Issue #399

emendas/modulos/principal/beneficiario_form.inc, www/emendas/js/principal/beneficiario_form.js
Ao marcar TED sim, não exigir preenchimento de modalidade de pactuação para gera PI.
=> [MELHORIA] Inserir regra ao marcar TED. Issue #321

planacomorc/modulos/apoio/item-manutencao-form.inc, planacomorc/modulos/apoio/item-manutencao.inc, planacomorc/modulos/apoio/subitem-manutencao-form.inc, planacomorc/modulos/apoio/subitem-manutencao.inc, public/classes/controller/ManutencaoItem.inc, public/classes/controller/ManutencaoSubItem.inc
Por favor, não delete a Branch.
=> [MELHORIA] Criação de nova tela de apoio item / subitem. Issue #203 

monitora/classes/model/Ptres.inc, proposta/modulos/principal/proposta_form.inc, www/spo/_funcoes.php
Correção de importação de unidades de medida
=> [CORREÇÃO] Unidade(Unidade de Medida) e Produto. Issue #353 

docs/Autores.md, docs/Guia_de_operacao-desenvolvimento.md
Fluxo de trabalho do Git para correções e melhorias rápidas(hotfix).
=> [ UPDATE ] Atualização da documentação de Versionamento

includes/library/simec/Crud/Listing.php, includes/rodape_bootstrap.inc, includes/rodape_bootstrap_v3.inc
Alterando a cor das fontes da tabela de simular o usuário.
Signed-off-by: Leonardo Dos Santos Silva Barreiros <leossb36@gmail.com>
=> [ FIX ] Consertar cor da fonte do simular usuário. Issue #235

docs/Guia_de_operacao-desenvolvimento.md
Corrigindo desenhos de histórias, e inserindo um pouco mais de detalhes em algumas descrições.
=> [ UPDATE ] Correção no Guia de Operação de Desenvolvimento

proposta/classes/model/Proposta.inc, proposta/modulos/principal/proposta.inc, proposta/modulos/principal/proposta_form.inc, www/proposta/js/principal/proposta.js
Adicionado filtro na lista de proposta que traz resultados por subunidades vinculadas ao perfil.
=> [ UPDATE ] Módulo Proposta - Lista de Proposta. Issue #418 

proposta/classes/model/PrePlanoInterno.inc, proposta/modulos/principal/preplanointerno.inc
Criação de filtros na tela de pesquisa.
=> [MELHORIA] Proposta-Filtros-ListaPi. issue #417 

includes/library/simec/Grafico.php
=> [ FIX ] Planejamento - Correção tooltip gráfico. Issue #410 

seguranca/www/scripts_exec/spo_atualizarDotacao.php
Correção no relatório de funcionais compartilhadas com divergências.
=> [ FIX ] Planejamento Orçamentário - E-mail com relatórios. Issue #412

docs/Guia_de_operacao-desenvolvimento.md
Inserindo instruções pra inserir segundo comentário nos commits e inserindo explicação sobre o git diff.
=> Documentação - Guia de Operação e Desenvolvimento

planacomorc/modulos/principal/unidade/cadastro_pi.inc, planacomorc/modulos/principal/unidade/cadastro_pi_fnc.inc
Correção para não ser possível colocar um código superior a 15 caracteres conforme a restrição da base de dados.
=> [ HOTFIX ] Planejamento Orçamentário - Alterar Código PI.

monitora/classes/model/Ptres.inc, proposta/classes/controller/Proposta.inc, proposta/modulos/principal/proposta_form.inc
Correção pra quando o usuário desmarcar a funcional selecionada o sistema apagar os dados de Produto e Unidade de Medida ao invés de gerar erro interno no servidor.
=> [ HOTFIX ] Proposta Orçamentária - Carregar descrição do Produto e Unidade

proposta/classes/model/PrePlanoInterno.inc
Correção de valores no painel de acompanhamento
=> [FIX] Proposta Painel de Acompanhamento. Issue. #395

proposta/modulos/principal/preplanointerno.inc, proposta/modulos/principal/proposta.inc
Correção de layout pra exibir corretamente a opção Pessoal e Encargos.
=> [ Hotfix ] Proposta Orçamentária - Filtro Enquadramento PI. Issue #445 

monitora/classes/Pi_PlanoInterno.class.inc
Correção na coluna de Programa, removendo duplicação de PIs e correção na exibição de PIs não exibindo os PIs indesejados.
Signed-off-by: Leonardo Dos Santos Silva Barreiros <leossb36@gmail.com>
=> [ FIX ] Planejamento Orçamentario - Correção no Relatório Geral. Issue #381

proposta/classes/controller/PrePlanoInterno.inc
Retirar a obrigatoriedade no campo de esfera.
=> [FIX] Proposta Tela Cadastro de Pré-PI - Salvar Pré-PI. Issue #455.

includes/cadastro_usuario_geral.php
Alterada a exibição da nomeclatura dos nomes dos módulos no sistema de segurança do projeto
=> [ UPDATE ] Módulo SIS - Exibição de nome dos módulos.

seguranca/www/scripts_exec/spo_atualizarDotacao.php, seguranca/www/scripts_exec/spo_atualizarExecucaoOrcamentaria.php
Edentando consultas utilizadas nas principais rotinas diárias.
=> [ REFACTORY ] Planejamento Orçamentário - Rotina diária

includes/erros.inc, includes/failure/ErrorHandler.php, includes/failure/ExceptionHandler.php
Alterado nome para mensagens de erro de erro no simec para erro no siminc2
=> [ UPDATE ] E-mail de Erro no ambiente

planacomorc/modulos/apoio/area_cultural_form.inc, planacomorc/modulos/apoio/segmento-cultural.inc, public/classes/controller/AreaCultural.inc, public/classes/controller/SegmentoCultural.inc
Correção na tela de area/segmento cultural
=> [ HOTFIX ] Correção da utilização da classe upper-text

global/controleInicio.inc, includes/controla_requisicao_upload.php, includes/rodape_bootstrap_v3.inc, public/classes/Model/ArquivoModulo.inc, public/classes/controller/ArquivoModulo.inc, public/lista_arquivos_modulo.inc, public/modal_upload_modulo.inc, www/geral/formUploadArquivo.php, www/includes/funcoes.js
=> [ADD] Anexos de Documentos. Issue #80 

global/database_producao.dist.php
Retirando documentação interna de bases de dados que não estão sendo utilizadas.
=> [FIX]Documentação Interna-Configuração

includes/funcoes.inc
Alterando ícone de apoio e configuração.
=> [FIX]Menu-Apoio

monitora/classes/Pi_PlanoInterno.class.inc, planacomorc/classes/controller/HistoricoPi.inc, planacomorc/classes/model/HistoricoPi.inc, planacomorc/modulos/principal/unidade/cadastro_pi.inc, planacomorc/modulos/principal/unidade/historico_pi_modal.inc, www/planacomorc/js/cadastro_pi_init.js
Adicionado o modal que listara as alterações feitas no código de PI.
=> [FIX] Módulo Planejamento - Melhoria no Cadastro de PI. Issue #79 

seguranca/modulos/sistema/menu/aba.inc
Alterado a consulta que filtrava todos os Sistemas da base de dados, filtrando agora apenas os Sistemas Ativos
=> [ FIX ] Módulo SIS - Melhorias no Combo de Sistemas Atuais Ativos.

public/classes/Model/ArquivoModulo.inc, public/lista_arquivos_modulo.inc, public/modal_upload_modulo.inc
[ FIX ] Criar tela para Documentos importantes. Issue #80
=> [ HOTFIX ] Criar tela para Documentos importantes. Issue #80

planacomorc/modulos/principal/unidade/painel.inc
Correção no filtro do ano na consulta da listagem das propostas.
=> [UPDATE] Planejamento cadastro unidade/subunidade. Issue #485 

planacomorc/modulos/apoio/SubUnidadeOrcamentaria_form.inc, public/classes/controller/SubUnidadeOrcamentaria.inc
Criação do campo suosigla na tela de cadastro da unidade/subunidade.
=> [UPDATE] Planejamento cadastro de unidade/subunidade. Issue #485 

README.md
Melhorando descrição. Relacionando com o SIMEC e contando um pouco do histórico
=> Melhorando descrição

planacomorc/modulos/apoio/indicadorpnc.inc
Adicionando coluna de codigo dos indicadores PNC na tabela de listagem dos indicadores PNC
Signed-off-by: Leonardo Dos Santos Silva Barreiros <leossb36@gmail.com>
=> [UPDATE] Planejamento - melhoria no cadastro de metas/indicadores pnc. Issue #489

monitora/classes/Pi_PlanoInterno.class.inc
Adicionado Sql para restringir funcionais de emenda (RP6).
=> [ FIX ] Módulo Planejamento - Tela Limites das Subunidades. Issue #466

docs/Fluxo_Kanban.md, docs/Guia_de_operacao-desenvolvimento.md
Adicionado melhoria na comunicação interna da equipe para evitar problemas de publicação
=> [ ADD ] Documentação

proposta/classes/model/PrePlanoInterno.inc
Correção na consulta que trazia a listagem de funcionais.
=> [HOTFIX] Proposta painel de acompanhamento.

painel/modulos/sistema/tabelaapoio/cadastroacoes/formulario_acao.inc
Inserindo Data de entrega da ação e Produto.
=> [UPDATE]Painel/Gestão estratégica-Cadastro de ações estratégicas

www/geral/workflow/alterar_estado.php
Include de historicoPI para poder gerar o PI em Cadastro de Beneficiario
Signed-off-by: Leonardo Dos Santos Silva Barreiros <leossb36@gmail.com>
Co-authored-by: Guilherme Alcantara <glhr.alcantara2015@gmail.com>
=> [FIX] Emendas - Gerar PI. Issue #533

emendas/classes/model/Beneficiario.inc
Retirando duplicidade da lista.
=> [UPDATE]Cadastro de Emendas-Lista de Beneficiários

monitora/classes/Pi_PlanoInterno.class.inc, planacomorc/modulos/inicio.inc, planacomorc/modulos/principal/unidade/painel_fnc.inc
Adicionado botão para exportar planilha das unidades do painel fnc e planilha das ações do painel fnc.
=> [ADD]Planejamento-Painel FNC-Exportar Planilhas. Issue #474

includes/classes/Modelo.class.inc, planacomorc/classes/Pi_Complemento.class.inc, planacomorc/modulos/principal/unidade/cadastro_pi.inc, planacomorc/modulos/principal/unidade/cadastro_pi_fnc.inc, planacomorc/modulos/principal/unidade/espelho-pi.inc, planacomorc/modulos/principal/unidade/modal-ptres-grafico.inc, proposta/classes/model/PrePlanoInterno.inc, www/emendas/_funcoes.php, www/planacomorc/_funcoespi.php
Correção de duplicação de dados na base e correção de estrutura de dados da tabela de complemento do PI.
=> [UPDATE]Cadastro de Emendas-Gerar PI. Issue #541 

acompanhamento/modulos/sistema/usuario/altsenha.inc, proposta/modulos/sistema/usuario/altsenha.inc
Incluindo layout novo da funcionalidade de alterar senha.
=> [FIX]Monitoramento e Proposta Orçamentária-Alterar Senha

www/planacomorc/_funcoespi.php
Correção na consulta do espelho de PI.
=> [CORREÇÃO] Cadastro de Emendas - Delegacao. Issue #554

proposta/modulos/principal/proposta_form.inc
Alterações nos nomes dos inputs do cadastro de proposta.
=> [UPDATE] Módulo Proposta - Cadastro de Proposta. Issue #557

seguranca/www/scripts_exec/spo_atualizarExecucaoOrcamentaria.php
Correção na função de atualização dos dados do WebService.
=> [ FIX ] Módulo Planejamento - Execução Orçamentária. Issue #559.

monitora/classes/model/PiEnquadramentoDespesa.inc, planacomorc/classes/model/ResultadoPrimario.inc, proposta/classes/controller/Proposta.inc, proposta/classes/model/Proposta.inc, proposta/classes/model/TipoDetalhamento.inc, proposta/modulos/principal/proposta_form.inc, www/proposta/js/principal/proposta_form.js
Retirando campo de Tipo de Detalhamento do formulário de Cadastro de Proposta e inserindo regra pra preencher Tipo de Detalhamento automaticamente na Planilha de Envio pra o SIOP.
=> [ADD]Cadastro de Proposta-Tipo de Detalhamento/Grupo. Issue #557 

proposta/classes/model/Proposta.inc, www/proposta/_funcoes.php
Correções em coluna de dados e duplicações.
=> [UPDATE]Proposta Orçamentária-Relatórios de Proposta. Demanda Issue #569 

proposta/classes/model/Proposta.inc, proposta/modulos/relatorio/proposta-unidade-siop.inc
Inserindo dados de subunidade do detalhamento da proposta.
=> [UPDATE]Proposta Orçamentária-Relatório Proposta por Unidade(SIOP)

includes/cabecalho_bootstrap_v3.inc
Correção no include do rodapé.
=> [FIX] Módulo Monitoramento - Rodapé

www/includes/estouvivo.js
Comentado a função javascript que chamava o arquivo estouvivo.php
=> [FIX] Módulo SIS.

planacomorc/modulos/principal/unidade/espelho-pi.inc, www/planacomorc/_funcoespi.php
Inserindo subunidade e sigla e mudando o nome de Unidade pra Unidade delegada.
=> [UPDATE]Módulo Planejamento-Espelho de PI. Issue. #552 

acompanhamento/modulos/relatorio/proposta/relatorio_form.inc, acompanhamento/modulos/relatorio/relatorio_principal_form.inc
Aliando as labels para deixar no padrão do sistema e ajustando exibição dos campos RP e Tipo de Detalhamento.
=> [UPDATE]Gerador de relatórios-Relatório Propostas. Issue #520 

emendas/modulos/principal/beneficiario_form.inc
Correção no tamanho máximo do textarea.
=> [FIX] Módulo Emendas - Cadastro de Beneficiário.

acompanhamento/classes/model/Historico.inc, acompanhamento/modulos/principal/historico.inc, planacomorc/classes/model/HistoricoPi.inc, planacomorc/classes/model/HistoricoPiUsuario.inc, planacomorc/modulos/principal/unidade/historico_pi_modal.inc, planacomorc/modulos/principal/unidade/historico_pi_usuario_modal.inc
Adicionado mais detalhes sobre os usuários nas modais de histórico de alterações.
=> [ADD]Módulo Planejamento-Cadastro de PI. Issue #598 

planacomorc/modulos/principal/unidade/cadastro_pi.inc, planacomorc/modulos/principal/unidade/cadastro_pi_fnc.inc, www/planacomorc/js/cadastro_pi_init.js
Foi removido o alerta que ficava aparecendo na hora de reduzir o valor do cronograma.
=> [CORREÇÃO]Cadastro de PI - Cronogramas. Issue #604

includes/email-template.php, planacomorc/classes/controller/ImportaDadosSiop.inc
Correção para enviar e-mail tanto ao executar a rotina diária quanto em outras funcionalidades do sistema como a de liberação de acesso a novos usuários.
=> [FIX]Gerenciar Usuário-Envio Email. Issue #613 

planacomorc/modulos/inicio.inc, proposta/classes/model/PrePlanoInterno.inc, proposta/modulos/inicio.inc, proposta/modulos/principal/montaGraficoExpansao.inc, proposta/modulos/principal/montaGraficoNormal.inc
Inserindo funcionalidade de exibir o painel apresentando apenas os dados das Unidades vinculadas ao perfil do Usuário do tipo Unidade.
=> [ADD]Painel de Acompanhamento-Perfil Subunidade. Issue #562

planacomorc/classes/controller/ImportaDadosSiop.inc
Correção para o problema de envio de e-mail.
=> [UPDATE]Rotina Diária-Atualização. Issue #633

www/painel/_funcoes.php
Alterado o nome dos campos de legenda do gráfico das metas dos indicadores, de acordo com a unidade de medição do indicador.
=> [MELHORIA] Módulo Painel - Gráfico de Metas do Indicador. Issue #615

painel/modulos/relatorio/indicadores-secretaria.inc
Corrigindo campo de orçamento pra o formato de moeda.
=> [UPDATE]Indicadores-Relatório de Indicadores por Secretarias. Issue #632

planacomorc/classes/controller/ImportaDadosSiop.inc, planacomorc/modulos/inicio.inc, seguranca/www/scripts_exec/spo_atualizarExecucaoOrcamentaria.php, spo/ws/sof/Quantitativo.php
Nova mensagem de erro para o usuário avisando que não foi possível atualizar os dados de execução orçamentário por instabilidade no Webservice do Sistema SIOP.
=> [UPDATE]Webservice SIOP-Atualizar Execução Orçamentária. Issue #539 

painel/classes/model/Indicador.inc
Classe Indicador adicionada ao modulo painel.
=> [ADD] Painel Classe Indicador.

painel/modulos/principal/lista.inc
Correção na excluisão de indicadores.
=> [HOTFIX]:fire::wrench: Painel - Lista de Indicador.

painel/modulos/inicio.inc
Alterado o redirecionamento da página inicial do módulo painel.
=> [CORREÇÃO] Painel - Redirecionamento Inicial. Issue #656

painel/modulos/principal/listarMetasIndicador.inc
Alteração do select para ordenar de acordo com o campo secordem.
=> [UPDATE] Painel Lista Metas. Issue #657

painel/modulos/principal/metaIndicador.inc, www/painel/_funcoes.php
Alteração no gráfico das metas, para trazer as séries históricas zeradas.
=> [UPDATE]Painel Grafico das Metas. Issue #664

painel/modulos/principal/cadastro.inc
Remoção da crítica de alteração da série histórica no momento de cadastrar um novo indicador.
=> [CORREÇÃO]Painel Cadastro de Indicadores. Issue #698

painel/modulos/relatorio/indicadores-secretaria.inc, www/painel/_funcoes.php
Correção no layout dos campos, implementação do thumbs na coluna observação.
Alterar a Regra das cores, colocando verde para tudo que for realizado maior ou igual a meta.
Mudar barra de progresso para a coluna de realizado
Coluna Orçamento depois de produto
Coluna Observação por último
Fixar Largura das colunas
Colocar Avaliação do Gestor (thumbsup, thumbsdown, exclamação), no começo da linha
=> [MELHORIA]Painel Relatório de Indicadores

painel/modulos/principal/avaliacaoGestor.inc
Implementação do ícone exclamação.
Criar mais um ícone para avaliação do gestor de acompanhamento(exclamação)
=> [MELHORIA]Painel Avaliação do Gestor

painel/modulos/principal/lista.inc
Correção na pesquisa da lista de indicadores.
=> [CORREÇÃO]Painel Lista de Indicadores

painel/modulos/principal/avaliacaoGestor.inc
Alteração de permissão para edição do campo observação na aba avaliação do gestor.
=> [CORREÇÃO]Painel Avaliação do Gestor

planacomorc/modulos/principal/unidade/cadastro_pi.inc, planacomorc/modulos/principal/unidade/cadastro_pi_fnc.inc, www/planacomorc/js/cadastro_pi_init.js
Correção na exclusão de processo e no upload de arquivos.
=> [FIX]Planejamento Cadastro de PI-Erro Anexo-Erro Processo. Issue #705

acompanhamento/modulos/relatorio/emendas/relatorio_form.inc, acompanhamento/modulos/relatorio/funcional/relatorio_form.inc, acompanhamento/modulos/relatorio/pi-fnc/relatorio_form.inc, acompanhamento/modulos/relatorio/pi/relatorio_form.inc, acompanhamento/modulos/relatorio/pre-pi/relatorio_form.inc, acompanhamento/modulos/relatorio/proposta/relatorio_form.inc, acompanhamento/modulos/relatorio/relatorio_principal_form.inc, includes/simec_funcoes.inc
Vinculação das subunidades dos usuários aos combos subunidades.
=> [ADD]Monitoramento Gerador de Relatório. Issue #694

www/cadastrar_usuario.php, www/login.php, www/recupera_senha.php, www/sigest.php
Corrigindo navegação dos botões cancelar/voltar das telas relacionadas ao login.
=> [UPDATE]Unificar os Sistemas GE e SIMINC2/PAINEL. Issue #734

includes/siop-soap-curl/quantitativo/service/execucao-orcamentaria.php, includes/siop-soap-curl/quantitativo/xml/execucao-orcamentaria.php, includes/siop-soap-curl/service.php, includes/siop-soap-curl/siop-soap-curl.php, includes/siop-soap-curl/xml.php
Corrigindo caminho físico de arquivos.
=> [FIX]WEBSERVICE SIOP-EXECUÇÃO ORÇAMENTÁRIA. Issue #727 

includes/siop-soap-curl/receita/service/captar-base-externa.php, includes/siop-soap-curl/receita/xml/captar-base-externa.php, includes/siop-soap-curl/siop-soap-curl.php, planacomorc/modulos/inicio.inc
=> [ADD]Atualização do WSSIOP

includes/siop-soap-curl/quantitativo/service/execucao-orcamentaria.php, includes/siop-soap-curl/quantitativo/xml/execucao-orcamentaria.php, planacomorc/classes/controller/ImportaDadosSiop.inc
Corrigindo lista de elementos repetidos no objeto de resposta XML.
=> [FIX]WEBSERVICE SIOP-EXECUÇÃO ORÇAMENTÁRIA. Issue #727

LICENSE
Adicionado liçença GPL2 ao projeto.
=> [MELHORIA] Licença.

painel/modulos/principal/cadastroEstrategiaMetas.inc, painel/modulos/principal/valorMetasIndicador.inc, painel/modulos/relatorio/indicadores-secretaria.inc, www/painel/_funcoes.php, www/painel/_funcoes_metas.php
Alterando de Meta Atual para Previsto, retirando coluna de Unidade de Medida do relatório e alterando título da aba, tela e colunas de Estratégia de metas para Legendas.
=> [UPDATE]Relatório-Indicadores por Secretarias-Meta Atual. Issue #765

painel/modulos/principal/cadastro.inc, painel/modulos/relatorio/indicadores-secretaria.inc, www/painel/_funcoes.php
Adicionado campo de Produto no Cadastro de Indicadores, adicionado este campo no relatório de indicadores, e consequentemente o resultado estará refletido no portal.
=> [ADD] Painel - Cadastro de Indicadores. Issue #768

includes/classes/Modelo.class.inc, monitora/classes/Pi_PlanoInterno.class.inc, monitora/classes/model/Ptres.inc, planacomorc/classes/controller/ImportaDadosSiop.inc, planacomorc/classes/controller/Unidadegestoralimite.inc, planacomorc/classes/model/ImportaDadosSiop.inc, planacomorc/modulos/apoio/unidadegestora-limite.inc, www/planacomorc/_constantes.php
Inserindo atualização automática de Funcionais do FNC. Correção do relatório de alteração de dotação e Valores empenhados sem código de PI.
=> [UPDATE]WEB SERVICE SIOP-Atualizar Dotações FNC. Issue #793

painel/modulos/relatorio/indicadores-secretaria.inc
Adicionando mensagem de aviso para um melhor uso
=> [UPDATE]Gestão Estratégica-Painel de Relatório. Issue #711

monitora/classes/Pi_PlanoInterno.class.inc, planacomorc/classes/model/ImportaDadosSiop.inc, planacomorc/modulos/inicio.inc, planacomorc/modulos/principal/unidade/painel_fnc.inc, www/planacomorc/_constantes.php, www/planacomorc/js/painel.js
Refatorando consultas, forma de processamento da lista e inserindo os valores corretos de Provisionado, Empenhado, Liquidado e Pago.
=>  [FIX]Painel FNC-Execução Orçamentária. Issue #796 (Parcial)

monitora/classes/Pi_PlanoInterno.class.inc, planacomorc/modulos/inicio.inc, planacomorc/modulos/principal/unidade/painel_fnc.inc
Retirando consultas desnecessárias e corrigindo a exportação de planilhas no formato XLS.
=> [REFACTORY]Painel FNC-Execução Orçamentária. Issue #796

elabrev/www/_funcoesliberacao.php, global/config-exemplo.inc, includes/cadastro_usuario_geral.php, includes/classes/modelo/par/AtualizarEmpenhoPagamento.class.inc, includes/classes/modelo/par/EmailObras.class.inc, includes/classes/modelo/par/EmailPrazoProvidenciaRestricao.class.inc, includes/classes/modelo/par/RefreshMaterializedViewPar.class.inc, includes/failure/ErrorHandler.php, includes/failure/ExceptionHandler.php, includes/funcoes.inc, includes/mensagemregra/formulario.inc, painel/modulos/sistema/mensagemregra/formulario.inc, painel/modulos/sistema/mensagemregra/listar.inc, planacomorc/modulos/principal/dadosacoes/detalhardadosacoes.inc, www/cadastrar_usuario.php, www/cadastrar_usuario_2.php, www/cadastrar_usuario_2_sigest.php, www/geral/envia_email_geral.php
Envio de e-mail avisando solicitação de acesso.
=> [UPDATE]Primeiro Acesso-Envio de Email. Issue #749

docker-compose.yml
Retirando mapeamento de volumes para os arquivos de exemplo de configuração.
=> [UPDATE]Docker Compose. Issue #750

docker-compose.yml
Trocando o nome do container WEB e organizando o arquivo de configuração.
=> [REFACTORY]Docker Compose. Issue #750

docker-compose.yml
Corrigindo versão do container de aplicação WEB.
=> [FIX]Docker-Compose. Issue #750

painel/modulos/relatorio/indicadores-secretaria.inc, www/painel/_funcoes.php
Adicionado campo de ano e mês no relatório de indicadores.
=> [ADD]Gestão Relatorio de Indicadores. Issue #767

acompanhamento/classes/controller/Classificacao.inc, acompanhamento/classes/controller/Medida.inc, acompanhamento/classes/model/Classificacao.inc, acompanhamento/classes/model/Medida.inc, acompanhamento/modulos/apoio/classificacao_form.inc, acompanhamento/modulos/apoio/medida_form.inc
Correção na exclusão lógica da tela e validação do campo obrigatório.
=> [UPDATE] Monitoramento - Cadastro de Classificação. Issue #837

acompanhamento/modulos/principal/monitorar-ppa.inc
Modificando nome das opções da caixa de texto do Monitoramento da Meta e adicionado títulos auto-explicativos.
=> [UPDATE] Monitoramento - Monitoramento PPA. Issue #838

planacomorc/modulos/principal/unidade/tramitacao-lote-fnc.inc, planacomorc/modulos/principal/unidade/tramitacao-lote.inc, www/planacomorc/_funcoes.php
Correção para enviar o corpo do e-mail corretamente pra todos os PIs cujo o estado foi alterado.
=> [FIX]Tramitação em lote-Envio de e-mail. Issue #836

zimec/library/Simec/View/Helper/Element.php, zimec/library/Simec/View/Helper/Select.php, zimec/library/Simec/View/Helper/Textarea.php
…tos dos formularios do sistema.
=> [FIX]Correção para correta vinculação de Títulos com opções dos Formulários

acompanhamento/classes/model/AcompanhamentoArquivo.inc, acompanhamento/modulos/principal/listar-anexos-pnc.inc, acompanhamento/modulos/principal/monitorar-pi-request.inc, acompanhamento/modulos/principal/monitorar-pnc.inc, acompanhamento/modulos/principal/monitorar-ppa.inc
Corrigido a funcionalidade de upload de arquivo, convertido o charset para utf8 e listando perfeitamente.
=> [UPDATE] Monitoramento - Monitoramentar PPA. Issue #845

painel/modulos/inicio.inc, painel/modulos/principal/avaliacaoGestor.inc, painel/modulos/principal/cadastro.inc, painel/modulos/principal/lista.inc, painel/modulos/principal/preenchimentoSerieHistorica.inc, painel/modulos/principal/valorMetasIndicador.inc, www/painel/_funcoes_metas.php
Implementação do exercício no módulo.
=> [ADD]Gestão - Exercício. Issue #823

painel/modulos/principal/cadastro.inc
Adicionado campo de peso no cadastro de indicador.
=> [ADD] Gestão Orçamentária - Cadastro de Indicadores. Issue #770

monitora/classes/model/Acao.inc, monitora/classes/model/Ptres.inc, planacomorc/modulos/apoio/acao.inc, planacomorc/modulos/apoio/funcionais.inc, planacomorc/modulos/apoio/vincular-ptres.inc, planacomorc/modulos/inicio.inc, planacomorc/modulos/principal/unidade/detalhe-ptres.inc, planacomorc/modulos/principal/unidade/detalhe-subunidade.inc, planacomorc/modulos/relatorio/funcionais.inc, spo/classes/model/Ptres.php, www/planacomorc/_constantes.php, www/planacomorc/js/unidade/lista-pi-manter.js
…onalidade de exibição de PIs por funcionais e Popup de espelho.
=> [FIX]Corrigindo Relatório de Funcionais, Lista de PIs e Espelho de PI

planacomorc/classes/controller/ImportaDadosSiop.inc
Implementação para atualizar ano de 2018.
=> [UPDATE]Planacomorc Ws SIOP.

planacomorc/classes/controller/ImportaDadosSiop.inc
Correção emitindo email mais de uma vez.
=> [UPDATE]Planejamento Atualização SIOP.

planacomorc/classes/controller/ImportaDadosSiop.inc
=> [UPDATE]Ws Siop.

planacomorc/classes/controller/ImportaDadosSiop.inc
Correção paginação da solicitação do ws.
=> [UPDATE]Ws SIOP

www/acompanhamento/_funcoes.php
Correção em campo para totalizar
=> [UPDATE] Monitoramento relatórios.

monitora/classes/Pi_PlanoInterno.class.inc
Alteração da consulta que lista as funcionais na tela inicial.
=> [UPDATE]Planejamento Lista Inicio.

planacomorc/classes/controller/ImportaDadosSiop.inc
Enviar email somente para o ano atual, após atualizar os dados do SIOP
=> [UPDATE]Planejamento Atualização Siop

planacomorc/modulos/apoio/SubUnidadeOrcamentaria.inc, planacomorc/modulos/apoio/SubUnidadeOrcamentaria_form.inc, planacomorc/modulos/apoio/unidadeOrcamentaria.inc, planacomorc/modulos/apoio/unidadeOrcamentaria_form.inc, public/classes/controller/SubUnidadeOrcamentaria.inc, public/classes/controller/UnidadeOrcamentaria.inc
Corrigindo telas de administração de UO e Subunidades.
=> [HOTFIX]Cadastro de PI-Gerar Código. Issue #872

monitora/classes/Pi_PlanoInterno.class.inc
Correção da consulta do gráfico que traz valores dos limites das unidades.
=> [FIX] Planejamento Orçamentário - Gráfico Direita. Issue #887

planacomorc/modulos/principal/unidade/cadastro_pi.inc, www/planacomorc/js/cadastro_pi_validacoes.js
Remoção da critica para salvar pisem valor
=> [UPDATE]Planejamento Cadastro de PI

acompanhamento/classes/model/Acompanhamento.inc, acompanhamento/modulos/relatorio/relatorio-ppa-grafico.inc, monitora/classes/Pi_PlanoInterno.class.inc
Corrigindo funcionalidade de filtrar Objetivo e metas e performance das consultas.
=> [FIX]Relatório PPA com Gráfico. Issue #899

planacomorc/modulos/apoio/cadastro_meta_ppa.inc, planacomorc/modulos/apoio/listagem_meta_ppa.inc, planacomorc/modulos/apoio/objetivoppa.inc, planacomorc/modulos/apoio/objetivoppa_form.inc, public/classes/Model/IniciativaPpa.inc, public/classes/Model/ObjetivoMetaPpa.inc, public/classes/Model/ObjetivoPpa.inc, public/classes/controller/Iniciativappa.inc, public/classes/controller/Metappa.inc, public/classes/controller/Objetivoppa.inc
Feitas correções no cadastro de Objetivo ppa, assim como no de iniciativas e metas.
=> [FIX] Planejamento - ObjetivoPPA. Issue #909.

monitora/classes/model/Acao.inc
Feita correção na query de ação que listava o Unidade Orçamentária da tabela errada.
=> [FIX] Planejamento - Ação. Issue #909

README.md, docs/Autores.md
Feita atualização do nome do Ministério de Cultura para Cidadania.
=> [FIX] Documentação do Projeto.

global/config-exemplo.inc, includes/cabecalho_bootstrap_v3_relatorio.inc
=> [UPDATE]Alterar nome do Órgão do Projeto. Issue #900

planacomorc/modulos/apoio/objetivoppa_form.inc
Feita correção na limitação de tamanho de caractere do nome de Objetivo PPA.
=> [FIX] Planejamento - Objetivo PPA. Issue #909

planacomorc/modulos/apoio/SubUnidadeOrcamentaria.inc, planacomorc/modulos/apoio/funcionais_form.inc, spo/classes/model/Ptres.php, www/planacomorc/_constantes.php
Realizada correção na consulta para listar as Unidades.
=> [HOTFIX]Planejamento - Vincular PTRES. Issue #922

README.md
Inclusão de documentação dos módulos:
* Planejamento Orçamentário
* Emendas Parlamentares
=> [UPDATE]Incluir Documentação de domínio de negócio SIMINC2

planacomorc/modulos/principal/unidade/cadastro_pi.inc, spo/classes/model/Unidade.php, www/planacomorc/_funcoespi.php
alterando UO's com codigo do ministerio da cidadania para ministerio da cidadania - administração direta
=> [FIX]Cadastro de PI-Unidade Orçamentária. Issue #937

planacomorc/classes/controller/ImportaDadosSiop.inc, planacomorc/classes/model/ImportaDadosSiop.inc
Inserindo rotina pra retirar os valores de execução do antigo órgão Ministério da cultura(42000).
=> [FIX]Painel de Acompanhamento-Execução Orçamentária. Issue #957

sql/restore/grants.sql
Arquivo atual de dump e  grants para permissões de tabelas.
=> [UPDATE] Database - Grant e Dump.

planacomorc/classes/model/ImportaDadosSiop.inc
Corrigindo atualização de Dotações pra levar em consideração o cógido do localizador pra definir os valores.
=> [HOTFIX]Painel de Acompanhamento-Atualizar SIOP. Issue #965

planacomorc/modulos/principal/unidade/cadastro_pi_identificacao.inc, planacomorc/modulos/principal/unidade/cadastro_pi_informacoes_etapas.inc
Alterações em obrigatoriedade de campos.
=> [UPDATE] Planejamento - Cadastro de PI. Issue #934.

planacomorc/modulos/inicio.inc
Corrigindo codigo das UGs e alterando siglas no título dos gráficos.
=> [FIX]Planejamento Orçamentário-Painel de Acompanhamento. Issue #903

planacomorc/modulos/inicio.inc
Correção para exibir os dados da Subunidade.
=> [HOTFIX]Painel de Acompanhamento-Subunidade. Issue #980

planacomorc/modulos/principal/unidade/cadastro_pi.inc
Realizada validação para exibir abas somente para os pi's com estado aprovado.
=> [FIX] Planejamento Orçamentário - Cadastro de Plano Interno. Issue #978.

planacomorc/modulos/inicio.inc
Realizada correção para exibir no hint o valor disponível da funcional.
=> [FIX]Planejamento Orçamentário-Painel de Acompanhamento. Issue #984.

planacomorc/modulos/principal/unidade/cadastro_pi.inc, planacomorc/modulos/principal/unidade/cadastro_pi_localizacao_responsavel.inc, planacomorc/modulos/principal/unidade/cadastro_pi_metas_produto.inc, www/planacomorc/js/cadastro_pi_validacoes.js
Realizada remoção de obrigatoriedade de campos de objetivo ppa, meta ppa e responsaveis pelo projeto.
=> [FIX] Planejamento Orçamentário - Cadastro de Plano Interno. Issue #976.

docs/Autores.md
Adicionado data de saída de colaborador.
=> [ADD] Documento de Autores.

planacomorc/modulos/principal/unidade/cadastro_pi.inc, planacomorc/modulos/principal/unidade/cadastro_pi_identificacao.inc, www/planacomorc/js/cadastro_pi_validacoes.js
Corrigindo validação de Limite de Subunidade e Funcional para PIs com enquadramento Não Orçamentário.
=> [HOTFIX]Cadastro de PI-Não orçamentário. Issue #990

monitora/classes/Pi_PlanoInterno.class.inc
Melhorando performance da consulta.
=> [HOTFIX]Planejamento Orçamentário-Acompanhamento de Funcionais. Issue #992

planacomorc/modulos/inicio.inc, planacomorc/modulos/principal/unidade/cadastro_pi.inc, planacomorc/modulos/principal/unidade/cadastro_pi_fnc.inc, planacomorc/modulos/principal/unidade/listapimanter.inc, planacomorc/modulos/principal/unidade/listapimanter_fnc.inc, planacomorc/modulos/principal/unidade/painel_fnc.inc
Trocado nome de botões de "...PI..." para "...PA..."
=> [HOTFIX]Planejamento-Mudanca de Nomes. Issue #998

planacomorc/modulos/principal/unidade/listapa-nao-orcamentaria-xls.inc, planacomorc/modulos/principal/unidade/listapa-nao-orcamentaria.inc, spo/classes/model/Planointerno.php, www/planacomorc/js/unidade/lista-pi-manter.js
Criado tela de gerenciamento de Planos de Ações do enquadramento do tipo 'Não Orçamentário'.
=> [HOTFIX]Planejamento- Lista PA Não Orçamentário. Issue #1004

planacomorc/modulos/principal/unidade/cadastro_pi.inc
Realizada correção de encoding de arquivo de anexo.
=> [FIX]Planejamento-Cadastro Plano de Ação. Issue #1009.

acompanhamento/modulos/principal/monitorar-pi-cad.inc, spo/classes/model/Planointerno.php
Retirado código da subunidade da lista de Planos de Ações Não Orçamentários e mudado legenda da aba de monitoramento da tela de cadastro.
=> [FIX]Planejamento-Lista PA Não Orçamentário. Issue #1011.

planacomorc/modulos/principal/unidade/cadastro_pi_identificacao.inc, www/planacomorc/_constantes.php
Realizado melhoria para trazer como default a opção não orçamentário quando for um formulário novo.
=> [FIX]Planejamento-Cadastro PA.

planacomorc/modulos/inicio.inc, www/planacomorc/js/painel.js
Realizada remoções do botão de atualizar siop e adicionado um botão de Ações não orçamentárias.
=> [FIX]Planejamento-Botões do Painel. Issue #1014

planacomorc/modulos/principal/unidade/cadastro_pi_identificacao.inc
Correção na combo de enquadramento de despesa checked por default.
=> [HOTFIX]Planejamento-Cadastro PA.

acompanhamento/classes/controller/Acompanhamento.inc, acompanhamento/modulos/principal/monitorar-pi-cad.inc, includes/funcoes.inc
=> [HOTFIX]Planejamento-Cadastro PA Aba Monitoramento. Issue #1020

planacomorc/modulos/inicio.inc
Habilitando botão de novo Cadastro de PA pra todos os perfis que não sejam Consulta e Consulta Unidade.
=> [HOTFIX]Cadastro de PI-Monitoramento-Medidas. Issue #1013

planacomorc/modulos/principal/unidade/cadastro_pi.inc, www/planacomorc/js/cadastro_pi_funcoes.js
Realizada alterações no formulário de PA quando o enquadramento for não orçamentário inverter o nome dos campos de Metas com o de Diretriz Estratégica.
=> [FIX]Planejamento-Cadastro PA. Issue #1030

monitora/classes/controller/Ptres.inc, monitora/classes/model/Acao.inc, planacomorc/modulos/apoio/acao.inc, planacomorc/modulos/apoio/acao_form.inc, planacomorc/modulos/apoio/funcionais_form.inc
Foi mudado os formulários de funcionais e ações para ser possível definiar Função e Subfunção no nível da ação e não da funcional.
=> [HOTFIX]Atualizar Funcionais Novas-Função Subfunção. Issue #994

monitora/classes/Pi_PlanoInterno.class.inc, planacomorc/modulos/principal/unidade/cadastro_pi_metas_produto.inc, planacomorc/modulos/relatorio/geral.inc
Adicionado colunas no relatório dos campos de diretriz, metas e objetivos estratégicos.
=> [MELHORIA]Planejamento-Objetivo Estratégico, Meta, Diretriz Estratégica-Relatório Geral. Issue #1049 

acompanhamento/modulos/principal/monitorar-pnc.inc
Retirada a validação de permissão de avanço de etapa no formulário de indicador pnc.
=> [FIX]Monitoramento-Monitoramento PNC. Issue #1054.

acompanhamento/classes/model/Acompanhamentopnc.inc
Adicionada condição para ordenar a lista de indicadores pnc por ordem alfabetica.
=> [ADD]Monitoramento-Indicador PNC. Issue #1055

spo/classes/model/Planointerno.php
Correção na consulta para subunidades.
=> [FIX]Planejamento-Lista PA Não Orçamentária. Issue #1058.

planacomorc/modulos/principal/unidade/cadastro_pi_identificacao.inc, www/planacomorc/_funcoespi.php
Realizada correção de erro de programação para salvar informação inserida no campo de Recursos Necessários.
=> [FIX]Planejamento-Cadastro PA Não Orçamentário. Issue #1044

planacomorc/modulos/inicio.inc
Removido o código da unidade gestora da tela Painel de Acompanhamento.
=> [FIX]Planejamento-Painel de Acompanhamento. Issue #1039

planacomorc/modulos/apoio/diretriz_estrategica_form.inc, planacomorc/modulos/apoio/meta_estrategica_form.inc, planacomorc/modulos/apoio/objetivo_meta_diretriz_form.inc
Adicionado implementação para submeter ao pressionar enter.
=> [ADD]Planejamento-Objetivo Estratégico, Meta, Diretriz Estratégica. Issue #1049

planacomorc/modulos/configuracao/vincular-meta-estrategica.inc
Inserindo código da subunidade pra facilitar uso de vinculação da tela.
=> [UPDATE]Objetivo Estratégico, Meta, Diretriz Estratégica. Issue #1049

monitora/classes/Pi_PlanoInterno.class.inc
Implementada correção para trazer PA'S delegado a unidade.
=> [ADD]Planejamento-Painel de Acompanhamento. Issue #1036.

acompanhamento/classes/controller/Acompanhamentopnc.inc, acompanhamento/modulos/principal/acompanhamento_indicador_pnc_form.inc, acompanhamento/modulos/principal/detalhe-pi-pnc.inc, acompanhamento/modulos/principal/monitorar-pnc.inc
Retiradas casas decimais e feita implementação para salvar sem casa decimal.
=>  [FIX]Monitoramento-Monitoramento PNC. Issue #1056

acompanhamento/modulos/relatorio/emendas/relatorio.inc, acompanhamento/modulos/relatorio/funcional/relatorio.inc, acompanhamento/modulos/relatorio/pi-fnc/relatorio.inc, acompanhamento/modulos/relatorio/pi/relatorio.inc, acompanhamento/modulos/relatorio/pre-pi/relatorio.inc, acompanhamento/modulos/relatorio/proposta/relatorio.inc, acompanhamento/modulos/relatorio/proposta/relatorio_form.inc, acompanhamento/modulos/relatorio/relatorio_principal_form.inc, includes/simec_funcoes.inc, www/proposta/_funcoes.php
Corrigindo estrutura da consulta pra quando o usuário tiver perfil de subunidade o sistema filtrar pelas unidades vinculadas ao usuário.
=> [HOTFIX]Monitoramento-Construtor de Relatórios. Issue #1043

planacomorc/modulos/principal/unidade/cadastro_pi_identificacao.inc
Adicionado maxlenght para limitar quantidades de caracteres do formulário de PA.
=> [HOTFIX]Planejamento-Cadastro PA. Issue #1087

acompanhamento/modulos/sistema/auditoria/auditoria.inc, alteracao/modulos/sistema/auditoria/auditoria.inc, emendas/modulos/sistema/auditoria/auditoria.inc, includes/classes/modelo/seguranca/Usuario.class.inc, monitora/modulos/sistema/auditoria/auditoria.inc, planacomorc/modulos/sistema/auditoria/auditoria.inc, proposta/modulos/sistema/auditoria/auditoria.inc
Melhorado o frontend da tela de pesquisa auditoria.
=> [FIX] Todos os Módulos - Auditoria.

acompanhamento/modulos/inicio.inc, acompanhamento/modulos/principal/monitorar-pi-cad.inc, monitora/classes/Pi_PlanoInterno.class.inc, public/classes/Model/SubUnidadeOrcamentaria.inc
Inserindo nova lista Meus Planos Não Orçamentários.
=> [ADD]Painel de Acompanhamento-Meus Planos de Ação Não Orçamentários. Issue #1041 

acompanhamento/modulos/inicio.inc, monitora/classes/Pi_PlanoInterno.class.inc, planacomorc/modulos/principal/unidade/espelho-pi.inc
Corrigindo colunas da tabela de PA Não Orçamentárias e corrigindo exibição do Popup de PA.
=> [HOTFIX]Painel de Acompanhamento-Meus Planos de Ação Não Orçamentárias. Issue #1041

includes/siop-soap-curl/service.php
Aumentado o tempo de espera da atualização de dotação.
=> [FIX]Planejamento-Correção de Dotações.

docs/Guia_de_operacao-desenvolvimento.md
Alterado o nome da branch de homologação.
=> [FIX]Documentação.

planacomorc/modulos/principal/pi/definicao_box.inc, www/planacomorc/_funcoespi.php
Retirando a opção Recursos necessários.
=> [DELETE]Cadastrar PA-Recursos necessários. Issue #1109

planacomorc/modulos/apoio/meta-unidade-form.inc
Alterando ordem dos campos de cadastro da meta unidade
=> [HOTFIX]Planejamento-Cadastro meta unidade. Issue #1136

emendas/classes/model/Emenda.inc, emendas/modulos/principal/beneficiario_form.inc, emendas/modulos/relatorio/geral.inc
Corrigindo lista de subunidades do cadastro de beneficiario
=> [FIX]Emendas - Cadastro Beneficiários-Subunidade. Issue #1106

planacomorc/modulos/apoio/meta-estrategica-form.inc
Correção para editar uma meta estratégica.
=> [FIX] Planejamento-Meta Estratégica.

emendas/modulos/inicio.inc, monitora/classes/model/Ptres.inc, www/emendas/js/principal/emenda.js
Ajustando filtro de Funcionais
=> [FIX]Emendas - Pesquisa avançada. Issue #1144

monitora/classes/Pi_PlanoInterno.class.inc
Corrigindo consulta para PA's Cancelados
=> [FIX]Planejamento - Tramitar PA em lote

monitora/classes/Pi_PlanoInterno.class.inc, www/planacomorc/_funcoes.php
Correção de valores totais com arredondamentos errados.
=> [HOTFIX]ROTINA DIÁRIA-Execução Orçamentária Liquidado. Issue #1120

monitora/classes/Pi_PlanoInterno.class.inc
Corrigindo valores duplicados de funcionais compartilhadas.
=> [FIX]Relatório de Funcionais-Duplicações. Issue #1160

README.md
OBS: Não excluir a branch, pois continuará sendo utilizada para inserir mais documentos
=> [FEATURE] Melhorando documentação SIMINC2. Inserção de história de usuário.

includes/classes/Modelo.class.inc, monitora/classes/Pi_PlanoInterno.class.inc, planacomorc/modulos/relatorio/funcionais-fnc.inc
Novo relatório de funcionais do Fundo Nacional de Cultura.
=> [ADD]Relatório de Funcionais FNC. Issue #1161
